# Deliverfile for UV Sense

# App Information
app_identifier("com.infuseproduct.UVchecker")

# Team Information
team_id("YH2Y8LT5HT")

# Metadata configuration
force(true) # Skip HTML report generation
submission_information({
  add_id_info_uses_idfa: false,
  add_id_info_serves_ads: false,
  add_id_info_tracks_install: false,
  add_id_info_tracks_action: false,
  add_id_info_limits_tracking: false,
  content_rights_has_rights: true,
  content_rights_contains_third_party_content: false,
  export_compliance_uses_encryption: false,
  export_compliance_is_exempt: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_contains_proprietary_cryptography: false
})

# Languages we support
# Fastlane uses specific locale codes for App Store Connect
languages([
  'en-US',      # English (U.S.)
])